
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 6.8
 PARAMETER PROC_INSTANCE = microblaze_0
 PARAMETER stdin = axi_uartlite_0
 PARAMETER stdout = axi_uartlite_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 2.8
 PARAMETER HW_INSTANCE = microblaze_0
 PARAMETER compiler_flags =  -mlittle-endian -mxl-soft-mul -mcpu=v11.0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_10
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_11
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_12
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_13
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_14
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_15
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_16
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_17
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_18
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_19
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_20
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_21
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_22
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_23
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_24
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_25
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_26
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_27
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_28
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_29
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_30
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_31
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_4
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_5
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_6
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_7
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_8
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = AudioVoice
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = AudioVoice_9
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_10
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_11
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_12
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_13
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_14
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_15
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_16
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_17
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_4
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_5
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_6
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_7
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_8
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = Sequencer_9
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = TempoGenerator_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = iic
 PARAMETER DRIVER_VER = 3.5
 PARAMETER HW_INSTANCE = axi_iic_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = axi_ps2
 PARAMETER DRIVER_VER = 1.0
 PARAMETER HW_INSTANCE = axi_ps2_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 3.2
 PARAMETER HW_INSTANCE = axi_uartlite_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = i2stx
 PARAMETER DRIVER_VER = 2.0
 PARAMETER HW_INSTANCE = i2s_transmitter_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 4.3
 PARAMETER HW_INSTANCE = mb_trigger_regs
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 3.8
 PARAMETER HW_INSTANCE = microblaze_0_axi_intc
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_dlmb_bram_if_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 4.2
 PARAMETER HW_INSTANCE = microblaze_0_local_memory_ilmb_bram_if_cntlr
END


