set_property PACKAGE_PIN R4 [get_ports SYSCLK]
create_clock -name SYSCLK -period 10 [get_ports {SYSCLK}] 
set_property IOSTANDARD LVCMOS33 [get_ports SYSCLK]

set_property PACKAGE_PIN G4 [get_ports RESET]
set_property IOSTANDARD LVCMOS15 [get_ports RESET]

set_property PACKAGE_PIN T5 [get_ports BCLK]
set_property IOSTANDARD LVCMOS33 [get_ports BCLK]
set_property PACKAGE_PIN W6 [get_ports DATA_O]
set_property IOSTANDARD LVCMOS33 [get_ports DATA_O]
set_property PACKAGE_PIN U5 [get_ports LRCLK]
set_property IOSTANDARD LVCMOS33 [get_ports LRCLK]
set_property PACKAGE_PIN U6 [get_ports MCLK]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
set_property PACKAGE_PIN W5 [get_ports IIC_RTL_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_RTL_scl_io]
set_property PACKAGE_PIN V5 [get_ports IIC_RTL_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_RTL_sda_io]

set_property PACKAGE_PIN M17 [get_ports TRIGGERS[0]]
set_property PACKAGE_PIN K13 [get_ports TRIGGERS[1]]
set_property PACKAGE_PIN J16 [get_ports TRIGGERS[2]]
#set_property PACKAGE_PIN H17 [get_ports TRIGGERS[3]]
#set_property PACKAGE_PIN G22 [get_ports TRIGGERS[4]]
#set_property PACKAGE_PIN G21 [get_ports TRIGGERS[5]]
#set_property PACKAGE_PIN F21 [get_ports TRIGGERS[6]]
#set_property PACKAGE_PIN E22 [get_ports TRIGGERS[7]]
#set_property PACKAGE_PIN D22 [get_ports TRIGGERS[8]]
#set_property PACKAGE_PIN C22 [get_ports TRIGGERS[9]]
#set_property PACKAGE_PIN B22 [get_ports TRIGGERS[10]]
#set_property PACKAGE_PIN D14 [get_ports TRIGGERS[11]]
#set_property PACKAGE_PIN F15 [get_ports TRIGGERS[12]]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[0]]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[1]]
set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports TRIGGERS[12]]

#set_property -dict { PACKAGE_PIN W17   IOSTANDARD LVCMOS33 PULLUP true } [get_ports { pclk }]; #IO_L16N_T2_A15_D31_14 Sch=ps2_clk
#set_property -dict { PACKAGE_PIN N13   IOSTANDARD LVCMOS33 PULLUP true } [get_ports { keyboard_data }]; #IO_L23P_T3_A03_D19_14 Sch=ps2_data
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets pclk_IBUF]

set_property PACKAGE_PIN N13 [get_ports PS2_Data_0_tri_io]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_Data_0_tri_io]
set_property PACKAGE_PIN W17 [get_ports PS2_Clk_0_tri_io]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_Clk_0_tri_io]
set_property PULLUP true [get_ports PS2_Clk_0_tri_io]
set_property PULLUP true [get_ports PS2_Data_0_tri_io]

set_property PACKAGE_PIN AA19 [get_ports usb_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_txd]
set_property PACKAGE_PIN V18 [get_ports usb_uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_rxd]